### ISSUE TITLE
allowedAppends not work anymore in V5 ?

### ISSUE THREAD

**Issue by JeremyPinto** [spatie/laravel-query-builder#736] opened 2022-03-02 14:11 UTC
Appending attributes has been removed from V4 to V5 : https://spatie.be/docs/laravel-query-builder/v4/features/appending-attributes.

The following code returns an error
->allowedAppends(['fullname']) 

What is the alternative to this in the last version ?

Thanks,

**Comment by dominikb** [comment] 2022-03-04 13:38
Duplicate of #725

**Closed** 2022-07-05 10:00 UTC
