### ISSUE TITLE
PHPStan doesn't know the return type of QueryBuilder

### ISSUE THREAD

**Issue by genesiscz** [spatie/laravel-query-builder#953] opened 2024-06-30 16:49 UTC
Hello,

I am not sure if I am missing something but let me explain.

When I do 

```php
        $formFields = FormField::query()->where("id", $formField->id);
        $a = $formFields->firstOrFail();
        \PHPStan\dumpType($a);

        $b = QueryBuilder::for(FormField::query()->where('id', $formField->id))
            ->allowedIncludes(['formFieldSelectItems'])
            ->get();

        \PHPStan\dumpType($b);

```

I recieve 

```
 45     Dumped type: App\Models\Forms\FormField                                                                                                                                                            
  51     Dumped type: Illuminate\Database\Eloquent\Collection<int, Illuminate\Database\Eloquent\Model>       
```

I feel like the collection should be automatically inferred or somehow working without PHPDocs, shouldn't it? 
I have this line in FormField:

`@method static Builder<FormField>|FormField query()`

Am I missing something or wasn't this thought of ?

Also, I think that the QueryBuilder should be generic in the first place, shouldn't be?

**Comment by AlexVanderbist** [comment] 2024-10-03 11:45
Hey, you're right! I was looking into this issue further and came across this fix that was recently tagged for phpstan and `Builder` objects. Can you check if this solves your issue? https://github.com/larastan/larastan/issues/2032

**Comment by AlexVanderbist** [comment] 2024-10-18 14:44
Closing this for now. Feel free to open a new issue referencing this one if the issue is still relevant. Thanks!

**Closed by AlexVanderbist** 2024-10-18 14:44 UTC

**Comment by matthiasPOE** [comment] 2025-03-19 13:33
@genesiscz how did you solve this im currently running into the issue on larastan 2.9.14

**Comment by genesiscz** [comment] 2025-05-20 19:34
> [@genesiscz](https://github.com/genesiscz) how did you solve this im currently running into the issue on larastan 2.9.14

Sorry for the late reply, I believe this worked: 

stubs/phpstan/QueryBuilder.stub:
```php
<?php

namespace Spatie\QueryBuilder;

use Illuminate\Database\Eloquent\Builder as EloquentBuilder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\Relation;
use Illuminate\Http\Request;

/**
 * @template TModel of Model
 *
 * @mixin EloquentBuilder<TModel>
 */
class QueryBuilder
{
    /**
     * @var EloquentBuilder<TModel>|Relation<TModel, Model, mixed>
     */
    protected EloquentBuilder|Relation $subject;

    /**
     * @param  EloquentBuilder<TModel>|Relation<TModel, Model, mixed>  $subject
     */
    public function __construct(
        EloquentBuilder|Relation $subject,
        ?Request $request = null
    ) {}

    /**
     * @template T of Model
     *
     * @param  EloquentBuilder<T>|Relation<T, Model, mixed>|string  $subject
     * @return self<T>
     */
    public static function for(
        EloquentBuilder|Relation|string $subject,
        ?Request $request = null
    ): self {}

    /**
     * @param  string  $name
     * @param  mixed  $arguments
     * @return EloquentBuilder<TModel>|self<TModel>
     */
    public function __call($name, $arguments): EloquentBuilder {}

    /**
     * @return EloquentBuilder<TModel>
     */
    public function getEloquentBuilder(): EloquentBuilder {}

    /**
     * @return Relation<TModel, Model, mixed>|EloquentBuilder<TModel>
     */
    public function getSubject(): Relation|EloquentBuilder {}

}
```

app/Traits/CreatesSpatieQueryBuilder.php:
```
<?php

namespace App\Traits;

use Illuminate\Database\Eloquent\Builder;
use Spatie\QueryBuilder\QueryBuilder;

trait CreatesSpatieQueryBuilder
{
    /**
     * @template T of \Illuminate\Database\Eloquent\Model
     *
     * @param  class-string<T>|Builder<T>  $query
     * @return QueryBuilder<T>
     */
    private function getQueryBuilder(string|Builder $query): QueryBuilder
    {
        return QueryBuilder::for($query);
    }
}

```
