### ISSUE TITLE
Bug?: Nested with Dash/camelCase, is this a bug?

### ISSUE THREAD

**Issue by martinandersen3d** [spatie/laravel-query-builder#360] opened 2019-10-08 17:25 UTC
"spatie/laravel-query-builder": "^2.1",
------------------------------------------------

I'm not totally sure if this post is relevant, please delete if not. Maybe you already know :-)

But it looks like a bug?

**Fails:**
![2019-10-08 19_12_37-StrokesPlus](https://user-images.githubusercontent.com/19984581/66417887-41201800-ea01-11e9-9a36-cec7cb3f1748.png)

**Wins:**

![2019-10-08 19_15_35-StrokesPlus](https://user-images.githubusercontent.com/19984581/66417911-4d0bda00-ea01-11e9-947b-859aaf702a07.png)

----

And thanks for this awesome package, it's like superpowers on steroids ;-)

**Comment by dominikb** [comment] 2019-10-11 19:38
Hi, thanks for providing those screenshots.

Sadly, I was not able to reproduce this bug using the version __2.1.0__

There are test cases, that cover this feature:
https://github.com/spatie/laravel-query-builder/blob/e66471c34b28a9511bb545d8c8ec0164b2913301/tests/IncludeTest.php#L159-L167

Can you try running the test suite locally and see if those fail as well?

**Comment by AlexVanderbist** [comment] 2019-10-20 20:41
Yeah, I think this was fixed in #336 :)

**Closed** 2019-12-06 17:23 UTC
